# TODO unify with requirements.txt
# TODO use poetry

[project]
name = "stations-pipelines"
version = "0.1.0"

# Requirements
[dependencies]
Click = "^7.0"

[dev-dependencies]
black = { version = "^18.3-alpha.0", python = "^3.12" }

[build-system]
requires = [
    "setuptools >= 58.0.4"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target_version = ['py312']
