[project]
name = "stations-pipelines"
version = "0.1.0"

# Requirements
[dependencies]
Click = "^7.0"

[dev-dependencies]
black = { version = "^18.3-alpha.0", python = "^3.9" }

[build-system]
requires = [
    "setuptools >= 58.0.4"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target_version = ['py39']

# TODO add test dependencies
# testcontainers-core==0.0.1rc1
# testcontainers-postgres==0.0.1rc1
# pytest

# TODO update dependencies
