# This workflow checks the data sources for validity

name: Data source validity checks

on:
  schedule:
    # Runs the workflow every day at midnight
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9.18

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #      - name: Run integration tests (only)
      #        run: |
      #          pip install -r test/requirements.txt
      #          pytest -m "integration_test"

      - name: "[DE/BNA] Real data validity checks"
        run: |
          pip install -r test/requirements.txt
          pytest tests/integration/test_int_de_bna.py
