# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DB_NAME: gis
  DB_HOST: localhost
  DB_PORT: 54322
  DB_USER: docker
  DB_PASSWORD: docker
  DB_SCHEMA: friendly_fox

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.18"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .

      - name: Run tests
        run: |
          pip install -r test/requirements.txt
          python -m pytest -m "not check_datasource"
